Multisubmit rules
th2-net/th2-grpc-check1 pull request #51
Opened 2024-01-16 15:25 UTC by lumber1000

2024-01-18 07:05 UTC, Nikita-Smirnov-Exactpro requested changes

2024-01-18 07:05 UTC, Nikita-Smirnov-Exactpro commented on src/main/proto/th2_grpc_check1/check1.proto
> +    rpc multiSubmitRules(MultiSubmitRulesRequest) returns (MultiSubmitRulesResponse) {}
Please rename to submitMultipleRules(MultiRulesRequest) returns (MultiRulesResponse)

2024-01-18 07:05 UTC, Nikita-Smirnov-Exactpro commented on src/main/proto/th2_grpc_check1/check1.proto
> +}
```suggestion
message MultiRulesResponse {
    ChainID chain_id = 1; 
    repeated RuleResponse responses = 2;
}
```

2024-01-18 07:05 UTC, Nikita-Smirnov-Exactpro commented on src/main/proto/th2_grpc_check1/check1.proto
> +    int64 rule_id = 3; // Can be used for requesting response via 'waitForResult' method
```suggestion
message RuleResponse {
    RequestStatus status = 1;
    int64 rule_id = 2; // Can be used for requesting response via 'waitForResult' method
```

2024-01-18 07:14 UTC, Nikita-Smirnov-Exactpro commented
I have questions about chain id in submit multiple rules. 
1. Should check1 provide ability to submit rules to different chain id? It is related to chain id in each request
2. Should check1 create separate chain id for each rules? It is related to chain id in response

My opinion is check1 should handle the whole multiple rules request as request for one chain id. This behavior should cover test case needs, because as I know users doesn't use chain id or use fixed chain id for case.
@OptimumCode what do you think about these questions?

2024-01-18 08:20 UTC, lumber1000 commented
Currently check1 allows to submit to one chain or to multiple chains or to generate new chainId for every rule. Demo script uses both fixed chainId for some rules and generating new chainId in check1 for others.

2024-01-18 08:57 UTC, OptimumCode commented
> My opinion is check1 should handle the whole multiple rules request as request for one chain id. This behavior should cover test case needs, because as I know users doesn't use chain id or use fixed chain id for case. @OptimumCode what do you think about these questions?

I don't think it will look good with the current API state. Each rule request contains ChainID. So, it is expected that this chain ID will be used when the rule is submitted. At least I would expect that. If we apply your suggestion @Nikita-Smirnov-Exactpro the above won't be true and will look like an unexpected behavior for the user in my opinion.
We could introduce a top-level chain ID in MultiRulesRequest that could be used for all rules if a user didn't specify a chain ID for a particular rule. The same might be applied to the MultiRulesResponse, however, we should not remove the chain ID from the individual response per rule as some rules might have their own chain IDs.

With the current API, I would rather stick to the option the @lumber1000 used in the beginning.

2024-01-22 08:07 UTC, Nikita-Smirnov-Exactpro commented
> We could introduce a top-level chain ID in MultiRulesRequest that could be used for all rules if a user didn't specify a chain ID for a particular rule. The same might be applied to the MultiRulesResponse, however, we should not remove the chain ID from the individual response per rule as some rules might have their own chain IDs.

I like this option, in this case user can submit multiple rules under single chain.
Also, I would like to use common chain id as priority way, for example
```
top-level-chain-id: empty
  rule1-chain-d: empty
  rule2-chain-d: chain-a
  rule3-chain-d: empty
```
check1 generates new `chain-0` chain id and submits 1,3 rule under it. Responses for each rule has actual chain id

2024-01-29 06:11 UTC, Nikita-Smirnov-Exactpro commented on src/main/proto/th2_grpc_check1/check1.proto
> +    ChainID default_chain = 1;
Could we declare the common parent_event_id with the same logic:
each rule without parent event id takes the parent_event_id from rule request.

2024-01-30 13:47 UTC, Nikita-Smirnov-Exactpro approved these changes

2024-01-31 09:05 UTC, Nikita-Smirnov-Exactpro approved these changes

2024-01-31 09:07 UTC, merged